defaults: &defaults
  docker:
    - image: circleci/node:10

git-login: &git-login
  name: Setting up git user
  command: git config --global user.email ci@ls-age.com && git config --global user.name "ls-age CI"

version: 2
jobs:
  install-deps:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Installing npm dependencies
          command: npm ci
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Building app
          command: npm run build

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint sources
          command: npm run lint -- --format junit --output-file ~/reports/eslint.xml
      - store_test_results:
          path: ~/reports
          when: always
      - store_artifacts:
          path: ~/reports
          when: always

  test:
    <<: *defaults
    docker:
      - image: cypress/base:10
        environment:
          # Enable colors in the output
          TERM: xterm
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Running tests
          command: npm run test

workflows:
  version: 2

  test-and-deploy:
    jobs:
      - install-deps
      - build:
          requires:
            - install-deps
      - lint:
          requires:
            - install-deps
      - test:
          requires:
            - build
