defaults: &defaults
  docker:
    - image: circleci/node:10

git-login: &git-login
  name: Setting up git user
  command: git config --global user.email ci@ls-age.com && git config --global user.name "ls-age CI"

version: 2
jobs:
  install-deps:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps
      - run:
          name: Installing npm dependencies
          command: npm ci
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Building app
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - __sapper__
            - static/css

  export:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-api-cache
      - run:
          name: Exporting app
          command: npm run export
      - save_cache:
          key: v1-api-cache
          paths:
            - ./data/cache
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint sources
          command: npm run lint -- --format junit --output-file ~/reports/eslint.xml
      - store_test_results:
          path: ~/reports
          when: always
      - store_artifacts:
          path: ~/reports
          when: always

  test:
    <<: *defaults
    docker:
      - image: cypress/base:10
        environment:
          # Enable colors in the output
          TERM: xterm
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Put cypress binary in place
          command: mv /circleci/.cache/Cypress ~/.cache/Cypress
      - run:
          name: Running tests
          command: npm run test
      - store_test_results:
          path: test/report/report.xml
      - store_artifacts:
          path: test/report

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          <<: *git-login
      - run:
          name: Deploying to github pages
          command: |
            git log -1 --pretty=%B > ../message
            git clone git@github.com:ls-age/ls-age.github.io.git ../pages
            cp -r __sapper__/export/* ../pages
            cd ../pages
            git add .
            git commit -m "$(cat ../message)"
            git push origin master
            cd ../project
      - run:
          name: Deploy to ls-age.com
          command: node ./scripts/deploy.js

  lighthouse:
    <<: *defaults
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          <<: *git-login
      - restore_cache:
          keys:
            - v1-lighthouse-cache
      - run:
          name: Update lighthouse badges
          command: npx lighthouse-badges -o docs/assets -u https://ls-age.github.io
      - save_cache:
          key: v1-lighthouse-cache
          paths:
            - ~/.npm
      - run:
          name: Commit lighthouse badges
          command: |
            git add docs/assets
            if git diff --name-only --cached --exit-code; then
              echo "Nothing to commit";
            else
              git commit -m "docs(readme): Update lighthouse badges [ci skip]

              $(git log -1 --pretty=%B)"
              git push origin master
            fi

workflows:
  version: 2

  test-and-deploy:
    jobs:
      - install-deps
      - build:
          requires:
            - install-deps
      - test:
          requires:
            - build
      - export:
          requires:
            - build
      - lint:
          requires:
            - install-deps
      - deploy:
          requires:
            - test
            - export
            - lint
          filters:
            branches:
              only:
                - master
      - lighthouse:
          requires:
            - deploy
